// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = {
    wiki: {
      site_title: 'Total RP 3 Documentation',
      base_url: '/wiki',
      support_email: 'ellypse@totalrp3.info',
      copyright: 'Copyright © ' + new Date().getFullYear() + ' - <a href="http://raneto.com">Powered by Raneto</a>',
      excerpt_length: 400,
      page_sort_meta: 'sort',
      category_sort: true,
      image_url: '/images',
      content_dir: './content/',
      analytics: ""
    }
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config.js.map
