// Generated by CoffeeScript 1.10.0
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = mongoose.connect('mongodb://localhost/totalrp3');

}).call(this);

//# sourceMappingURL=database.js.map
