// Generated by CoffeeScript 1.10.0
(function() {
  var backgrounds, debug, router;

  debug = require('debug')('index');

  router = require('express').Router();

  debug('Importing UI tweaks backgrounds controller');

  backgrounds = appReq("/controllers/ui-tweaks/backgrounds");

  router.get('/', function(req, res) {
    var background, ref;
    debug('GET /');
    debug('Picking a random background');
    background = backgrounds.pickOne((ref = req.query.bg) != null ? ref : "");
    debug('Picked background:', background);
    debug('Rendering index view');
    return res.render("index", {
      background: background.slice(0, -4)
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
