// Generated by CoffeeScript 1.10.0
(function() {
  var router;

  router = require('express').Router();

  router.get('/', function(req, res) {
    return res.render("storyline/storyline");
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=storyline.js.map
