// Generated by CoffeeScript 1.10.0
(function() {
  var User, debug, isAuthenticated, passport, router;

  debug = require('debug')('user');

  router = require('express').Router();

  passport = require('passport');

  debug('Importing User service');

  User = appReq('/services/user-service');

  debug('Importing isAuthenticated method from passport');

  isAuthenticated = appReq("/controllers/authentication/passport-auth").isAuthenticated;

  router.get('/ ', isAuthenticated, function(req, res) {
    return debug('GET /user/');
  });

  router.get('/register', isAuthenticated, function(req, res) {
    var destination;
    debug('GET /user/register');
    debug('Current user', req.user);
    destination = req.session.destination || "/wiki";
    debug('User destination', destination);
    debug('Rendering user/register view');
    return res.render("user/register", {
      battletag: req.user.battlenet.battletag,
      destination: destination
    });
  });

  router.post('/register', isAuthenticated, function(req, res) {
    debug('POST /user/register');
    debug('Form data', req.body);
    debug('Current user', req.user);
    debug('Updating user in the database');
    return User.update({
      'battlenet.id': req.user.battlenet.id
    }, {
      username: req.body.username,
      email: req.body.email
    }, function() {
      debug('User updated');
      return res.json({
        status: 'ok'
      });
    });
  });

  router.get('/login', function(req, res) {
    debug('GET /user/login');
    debug('Rendering user/login view');
    return res.render("user/login");
  });

  router.get('/auth/bnet', passport.authenticate('bnet'));

  router.get('/auth/bnet/callback', passport.authenticate('bnet', {
    failureRedirect: '/'
  }), function(req, res) {
    debug('GET /user/auth/bnet/callback');
    debug('<called by Blizzard>');
    debug('User data', req.user);
    debug('Looking for an existing user in the database for ID', req.user.battlenet.id);
    return User.findById(req.user.battlenet.id, function(err, user) {
      if (err) {
        debug('Error while fetching the database', err);
        return;
      }
      if (!user) {
        debug('No user found for ID', req.user.battlenet.id);
        debug('Inserting a new user in the database for received data', data);
        User.addUser(req.user, function() {
          debug('User correctly inserted in the database');
          debug('Redirecting user to the registration page');
          return res.redirect('/user/register');
        });
      }
      debug('User found', user);
      if (req.session.destination) {
        debug('User has a destination set', req.session.destination);
        debug('Redirecting user to the destination', req.session.destination);
        return res.redirect(req.session.destination);
      } else {
        debug('User does not have a destination');
        debug('Redirecting user to the wiki (/wiki)');
        return res.redirect('/wiki');
      }
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=user.js.map
