// Generated by CoffeeScript 1.10.0
(function() {
  var debug;

  debug = process.env.DEBUG !== null;

  module.exports = {
    clientID: debug ? "73sqymavgu3jsqn8vf5d5gfh98tpx3ac" : "3c98a589tk4rh64xne4c5wytw3pd5w63",
    clientSecret: debug ? "5c4vdRDpDfCaaFUPb7RusGX6p3p6KS6M" : "p9mRFMnZBMFuRQUsxrfk3Av7kTJsZQHT",
    callbackURL: debug ? "https://localhost:3000/user/auth/bnet/callback" : "https://totalrp3.info/user/auth/bnet/callback",
    scope: 'wow.profile'
  };

}).call(this);

//# sourceMappingURL=battlenet-config.js.map
