// Generated by CoffeeScript 1.10.0
(function() {
  var error_handlers;

  error_handlers = function(app) {
    var debug;
    debug = require('debug')('routes');
    app.use(function(req, res, next) {
      var err;
      err = new Error('Not Found');
      err.status = 404;
      debug(err);
      return next(err);
    });
    return app.use(function(err, req, res, next) {
      debug(err);
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: app.get('env' === 'development') ? err : {}
      });
    });
  };

  module.exports = error_handlers;

}).call(this);

//# sourceMappingURL=error_handlers.js.map
