// Generated by CoffeeScript 1.10.0
(function() {
  var Locale;

  Locale = appReq('/models/locales');

  exports.addNewLocale = function(locale) {
    var newLocale;
    newLocale = new Locale({
      localeIdentifier: locale.localeIdentifier,
      localeName: locale.localeName,
      localeContent: locale.localeContent
    });
    newLocale.save();
    return newLocale;
  };

  exports.updateLocale = function(locale) {
    var newLocale;
    newLocale = new Locale({
      localeIdentifier: locale.localeIdentifier,
      localeName: locale.localeName,
      localeContent: locale.localeContent
    });
    newLocale.save();
    return newLocale;
  };

  exports.findAll = function() {
    return Locale.find().exec();
  };

  exports.findById = function(id, next) {
    return id;
  };

}).call(this);

//# sourceMappingURL=locale-service.js.map
