// Generated by CoffeeScript 1.10.0
(function() {
  var User;

  User = appReq('/models/user');

  exports.addUser = function(user, next) {
    var newUser;
    newUser = new User({
      username: user.battlenet.battletag,
      battlenet: {
        accessToken: user.accessToken,
        id: user.battlenet.id,
        battletag: user.battlenet.battletag
      }
    });
    return newUser.save(function(err) {
      return next(err ? err : void 0);
    });
  };

  exports.findById = function(id, next) {
    return User.findOne({
      'battlenet.id': id
    }, function(err, user) {
      if (err) {
        return next(err);
      } else {
        return next(null, user);
      }
    });
  };

  exports.update = function(condition, values, callback) {
    return User.update(condition, values, callback);
  };

}).call(this);

//# sourceMappingURL=user-service.js.map
