// Generated by CoffeeScript 1.10.0
(function() {
  var Locale, mongoose;

  mongoose = appReq('/database.js');

  Locale = mongoose.model('Locale', {
    localeIdentifier: String,
    localeName: String,
    localeContent: [
      {
        key: String,
        value: String,
        updated: {
          type: Date,
          "default": Date.now
        },
        valueEN: String,
        shouldBeUpdated: {
          type: Boolean,
          "default": true
        }
      }
    ]
  });

  module.exports = Locale;

}).call(this);

//# sourceMappingURL=locales.js.map
